# ----------- 默认配置选择 -----------
server:
  port: 8080
spring:
  profiles:
    active: dev
# --------------------------------------------
---
# --------------------------------------------
# --------------------------------------------
# ----------- 运行模式配置==开发模式 -----------
#图片上传路径映射 自定义属性
upload:
  picture:
    path: F:/upload/images
spring:
  profiles: dev
# ----------- springMVC相关配置 -----------
  mvc:
      date-format: yyyy-MM-dd
  messages:
    basename: i18n/login
  http:
      # 文件上传配置
      multipart:
        enabled: true
        file-size-threshold: 0
        location: F:/upload/images
        max-file-size: 1Mb
        max-request-size: 10Mb
# ----------- 数据源配置 -----------
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/studentinfo_mansys?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
# 建库文件
#    schema:
#      - classpath:mybatis/database.sql
# ---------------- rabbitmq消息服务配置 --------------------
  rabbitmq:
    host: 47.102.107.23
    username: chenu
    password: 147258
# ---------------- redis noSQL --------------------
  redis:
    host: 47.102.107.23
# ----------- thymeleaf配置 -----------
  thymeleaf:
    cache: false
    mode: HTML

# ----------- MyBatis相关配置 -----------
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
# ----------- 服务器相关配置 -----------
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
# ----------- 日志框架配置 -----------
logging:
  level:
    com.chenu.pvcstumansys: trace
  pattern:
    file: '%d{yyyy-MM-dd} ==> [%thread] ==> %-5level ==> %logger{50} ===> %msg%n'
# ----------- spring监控器配置 -----------
management:
  security:
    # 开发模式下，监控安全验证关闭
    enabled: false
endpoints:
  shutdown:
    # 打开远程关闭系统功能
    enabled: true
# ---------------- 其他配置 --------------------
debug: true
# --------------------------------------------

---

# ----------- 运行模式配置==生产模式 -----------
spring:
  profiles: prod
# ----------- 数据源配置 -----------
  datasource:
    username: root
    url: jdbc:mysql://47.102.107.23:3306/studentinfo_mansys?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
# 数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
# ---------------- rabbitmq消息服务配置 --------------------
  rabbitmq:
    host: 47.102.107.23
    username: chenu
    password: 147258
# ---------------- redis noSQL --------------------
  redis:
    host: 47.102.107.23
# ----------- thymeleaf配置 -----------
  thymeleaf:
    cache: true
    mode: HTML
# ----------- MyBatis相关配置 -----------
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xm
# ----------- 服务器相关配置 -----------
server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
# ----------- 日志框架配置 -----------
logging:
  pattern:
    console: '%d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n'
    file: '%d{yyyy-MM-dd} ==> [%thread] ==> %-5level ==> %logger{50} ===> %msg%n'
  # 在指定位置下生成日志文件，日志将自动输出到该文件中
  file: ./log/studentinfo_mansys.log
# ----------- spring监控器配置 -----------
management:
  security:
    # 开发模式下，监控安全验证打开
    enabled: true
endpoints:
  shutdown:
    # 关闭远程关闭系统功能
    enabled: false
# --------------------------------------------